//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEgyVision.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models_VerifyUserVM
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models_VerifyUserVM()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saree3Admin.Resources.Models.VerifyUserVM", typeof(Models_VerifyUserVM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Beneficiar Id.
        /// </summary>
        public static string BeneficiarId
        {
            get
            {
                return ResourceManager.GetString("BeneficiarId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter Beneficiar Id.
        /// </summary>
        public static string BeneficiarIdError
        {
            get
            {
                return ResourceManager.GetString("BeneficiarIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryKey
        {
            get
            {
                return ResourceManager.GetString("CountryKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter Country Code.
        /// </summary>
        public static string CountryKeyError
        {
            get
            {
                return ResourceManager.GetString("CountryKeyError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Family Name.
        /// </summary>
        public static string FamilyName
        {
            get
            {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter FamilyName.
        /// </summary>
        public static string FamilyNameError
        {
            get
            {
                return ResourceManager.GetString("FamilyNameError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FatherName
        {
            get
            {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter Father Name.
        /// </summary>
        public static string FatherNameError
        {
            get
            {
                return ResourceManager.GetString("FatherNameError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter First Name.
        /// </summary>
        public static string FirstNameError
        {
            get
            {
                return ResourceManager.GetString("FirstNameError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string LKCountryId
        {
            get
            {
                return ResourceManager.GetString("LKCountryId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please choose Nationality.
        /// </summary>
        public static string LKCountryIdError
        {
            get
            {
                return ResourceManager.GetString("LKCountryIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National Id.
        /// </summary>
        public static string NationalId
        {
            get
            {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter National Id.
        /// </summary>
        public static string NationalIdError
        {
            get
            {
                return ResourceManager.GetString("NationalIdError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter Mobile Number.
        /// </summary>
        public static string PhoneNumberError
        {
            get
            {
                return ResourceManager.GetString("PhoneNumberError", resourceCulture);
            }
        }
    }
}
